function render(view, title) {
  return (req, res) => res.render(view, { title });
}

const frontendController = {
  login: render("auth/login", "Admin login"),
  dashboard: render("dashboard/index", "Dashboard"),
  enquiries: render("enquiry/index", "Requirements"),
  enquiryCreate: render("enquiry/form", "Create requirement"),
  enquiryEdit: render("enquiry/form", "Edit requirement"),
  enquiryShow: render("enquiry/show", "Requirement details"),
  enquiryReview: render("enquiry/review", "Validation & qualification review"),
  enquiryNearbyProviders: render("enquiry/nearby-providers", "Nearby Providers"),
  enquiryProviderStatuses: render("enquiry/provider-statuses", "Unlocked providers"),
  enquiryProviderStatusShow: render("enquiry/provider-status-show", "Provider unlock details"),
  providers: render("provider/index", "Providers"),
  providerMap: (req, res) => res.render("provider/map", {
    title: "Provider map",
    googleMapsBrowserApiKey: String(process.env.GOOGLE_MAPS_BROWSER_API_KEY || "").trim(),
    googleMapsMapId: String(process.env.GOOGLE_MAPS_MAP_ID || "").trim(),
  }),
  providerRequests: render("provider-request/index", "Provider requests"),
  providerRequestShow: render("provider-request/show", "Provider request"),
  agents: render("agent/index", "Agents"),
  agentCreate: render("agent/form", "Create agent"),
  agentEdit: render("agent/form", "Edit agent"),
  agentShow: render("agent/show", "Agent details"),
  partnerWithdrawals: render("partner-payout/index", "Partner withdrawals"),
  partnerWithdrawalShow: render("partner-payout/show", "Partner withdrawal"),
  categories: render("category/index", "Categories"),
  serviceTypes: render("category/service-types", "Subcategories"),
  websiteServices: (req, res) => res.render("website-content/items", { title: "Website Services", kind: "service" }),
  websiteProducts: (req, res) => res.render("website-content/items", { title: "Website Products", kind: "product" }),
  websiteMedia: render("website-content/media", "Media Library"),
  websiteCatalogImport: render("website-content/csv-import", "Catalog CSV Import"),
  websiteHomepage: render("website-content/homepage", "Homepage Manager"),
  providerCreate: render("provider/form", "Create provider"),
  providerEdit: render("provider/form", "Edit provider"),
  providerShow: render("provider/show", "Provider details"),
  followUps: render("follow-up/index", "Follow-ups"),
  followUpCreate: render("follow-up/form", "Create follow-up"),
  followUpEdit: render("follow-up/form", "Edit follow-up"),
  communications: render("communication/channel-home", "WhatsApp communication"),
  communicationWhatsapp: render("communication/channel-home", "WhatsApp communication"),
  communicationEmail: render("communication/channel-home", "Email communication"),
  communicationEmailInternalAlerts: render("communication/internal-alerts", "Internal email alerts"),
  communicationWhatsappLogs: render("communication/logs", "WhatsApp message logs"),
  communicationEmailLogs: render("communication/logs", "Email message logs"),
  communicationLogs: render("communication/logs", "Message logs"),
  whatsappInbox: render("whatsapp-inbox/index", "WhatsApp Inbox"),
  communicationShow: render("communication/show", "Communication details"),
  communicationSend: render("communication/send", "Send message"),
  communicationTemplates: render("communication/templates", "Manage templates"),
  communicationWhatsappTemplates: render("communication/templates", "WhatsApp templates"),
  communicationEmailTemplates: render("communication/templates", "Email templates"),
  communicationTemplateCreate: render("communication/template-form", "Create template"),
  communicationTemplateEdit: render("communication/template-form", "Edit template"),
  communicationRules: render("communication/rules", "Manage automation rules"),
  communicationWhatsappRules: render("communication/rules", "WhatsApp automations"),
  communicationEmailRules: render("communication/rules", "Email automations"),
  communicationOtp: render("communication/otp", "OTP activity"),
  communicationSettings: render("communication/settings", "Channel management"),
  communicationCreate: render("communication/form", "Log communication"),
  communicationEdit: render("communication/form", "Edit communication"),
  invoices: render("invoice/index", "Invoices"),
  providerSubscriptions: render("billing/provider-subscriptions", "Provider Subscriptions"),
  invoiceCreate: render("invoice/form", "Create invoice"),
  invoiceEdit: render("invoice/form", "Edit invoice"),
  providerUnlocks: render("provider-unlock/index", "Provider unlocks"),
  reports: render("report/index", "Reports"),
  storage: render("storage/index", "File Manager"),
  employees: render("employee/index", "Employees"),
  employeeCreate: render("employee/form", "Create employee"),
  employeeEdit: render("employee/form", "Edit employee"),
  roles: render("role/index", "Roles and permissions"),
  roleCreate: render("role/form", "Create role"),
  roleEdit: render("role/form", "Edit role"),
};

module.exports = frontendController;
